#!/bin/sh /etc/rc.common

START=99

start() {
    # Log the start time
    echo "$(date) - Starting installcore script" >> /var/log/installcore.log

    # Ping localhost to simulate delay
    ping -c 30 127.0.0.1

    # Execute the installation script
    sh /root/installcore.sh
}
